import { Platform, PricingTier, NavItem, VoiceAgentConfig } from '@/types'

// Site info
export const SITE = {
  name: 'Corporate AI Solutions',
  tagline: "The factory that builds AI companies. One founder. Zero employees.",
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://corporateaisolutions.com',
  email: process.env.NEXT_PUBLIC_CONTACT_EMAIL || 'hello@corporateaisolutions.com',
  phone: process.env.NEXT_PUBLIC_CONTACT_PHONE || '+61402612471',
  phoneFormatted: '+61 402 612 471',
  company: 'Global Buildtech Australia Pty Ltd',
  abn: '54 672 395 685',
  location: 'Brisbane, Queensland, Australia',
}

// Founder info
export const FOUNDER = {
  name: 'Dennis McMahon',
  title: 'Founder & CEO',
  linkedin: 'https://www.linkedin.com/in/denniskl/',
  calendly: 'https://www.calendly.com/mcmdennis',
  youtube: 'https://www.youtube.com/@globalbuildtech',
  newsletters: {
    goOffsite: {
      name: 'Go Offsite',
      url: 'https://www.linkedin.com/newsletters/go-offsite-7016211191035289600/',
      description: 'Insights on modular construction and prefab building methods.',
    },
    biAiAdvantage: {
      name: 'BI AI Advantage',
      url: 'https://www.linkedin.com/newsletters/bi-ai-advantage-7218131009064640512/',
      description: 'Business intelligence meets AI for real business outcomes.',
    },
  },
  companies: {
    globalBuildtech: {
      name: 'Global Buildtech',
      url: 'https://www.global-buildtech.com',
      description: 'Modular construction consultancy. 30+ years of building expertise.',
    },
    factory2key: {
      name: 'Factory2Key',
      url: 'https://www.factory2key.com.au',
      description: 'Turnkey modular homes. SDA specialist. Where Checkpoint was born.',
    },
  },
}

// Skool community
export const SKOOL = {
  url: process.env.NEXT_PUBLIC_SKOOL_URL || 'https://www.skool.com/the-easily-distracted-5598',
  name: 'The Easily Distracted',
  tagline: 'No Funnels. No Gurus. Just Problems Worth Solving.',
  description: 'A community for late-night thinkers, chaos navigators, and real-world fixers who can\'t ignore a problem once they see it.',
}

// Navigation
export const NAV_ITEMS: NavItem[] = [
  {
    label: 'Solutions',
    href: '/solutions',
    children: [
      { label: 'All Solutions', href: '/solutions' },
      { label: 'High-Stakes Performance', href: '/solutions#performance' },
      { label: 'Business Intelligence', href: '/solutions#intelligence' },
      { label: 'Industry Solutions', href: '/solutions#industry' },
    ],
  },
  { label: 'Partner', href: '/partner' },
  { label: 'Pricing', href: '/pricing' },
  { label: 'Community', href: '/community' },
  {
    label: 'About',
    href: '/about',
    children: [
      { label: 'Our Story', href: '/about' },
      { label: 'Voice AI Approach', href: '/voice-ai' },
      { label: 'Investors', href: '/invest-in-the-future-of-ai' },
    ],
  },
]

// All platforms - Parent/Child Structure
// Parents are the main platforms to visit
// Children are examples of white-label output from generators

export const PLATFORMS: Platform[] = [
  // ============================================
  // PARENT PLATFORMS (Public Landing Pages)
  // ============================================

  // ----------------------------------------
  // CORE INFRASTRUCTURE LAYER
  // ----------------------------------------

  {
    id: 'platform-trust',
    name: 'Platform Trust',
    slug: 'platform-trust',
    tagline: 'Universal trust, security, and observability for AI platforms',
    problem: 'Production AI agents need security, audit trails, and compliance evidence — none of it comes free',
    description: 'The brakes layer for the entire platform portfolio. Six modules: automated security scanning, agent quality evals, structured audit logging, per-tenant token/cost metering, permission governance with human-in-the-loop gates, and rate limiting. Compliance evidence for Australian Privacy Act, OWASP Top 10, and SOC 2 readiness — installed as @platform-trust/middleware in every product.',
    url: 'https://platform-trust.vercel.app',
    status: 'live',
    category: 'infrastructure',
    hasVoiceAI: false,
    featured: true,
    type: 'parent',
  },
  {
    id: 'pubguard',
    name: 'PubGuard',
    slug: 'pubguard',
    tagline: 'Automated vulnerability scanning and OWASP compliance for AI platforms',
    problem: 'AI products ship to enterprises without documented security posture — buyers demand evidence',
    description: 'The security scanning engine inside Platform Trust. Runs on PR merge, deploy events, and weekly cron: dependency audits, secret exposure checks, API endpoint classification (read/write, auth-required), agent tool permission surface analysis, and the OWASP Top 10 checklist for API surfaces. Outputs severity-graded findings, downloadable PDF compliance reports for buyer sign-off, and public compliance badges.',
    url: 'https://kira-rho.vercel.app/pubguard/scan',
    status: 'live',
    category: 'infrastructure',
    hasVoiceAI: false,
    type: 'parent',
  },

  // ----------------------------------------
  // GENERATOR PLATFORMS
  // ----------------------------------------

  // Voice Coaching Suite
  {
    id: 'rehearsals-ai',
    name: 'Rehearsals AI',
    slug: 'rehearsals-ai',
    tagline: 'The suite of AI voice coaching verticals',
    problem: 'High-stakes conversations need practice',
    description: 'Our platform generation model for AI voice coaching. Multiple verticals built and ready to spin up for any industry that needs conversation practice.',
    url: 'https://rehearsals-ai.vercel.app',
    status: 'live',
    category: 'generators',
    hasVoiceAI: true,
    featured: true,
    type: 'parent',
    isGenerator: true,
  },
  {
    id: 'raiseready-template',
    name: 'RaiseReady Template',
    slug: 'raiseready-template',
    tagline: 'White-label founder/investor platform generator',
    problem: 'Founders need pitch practice, investors need deal flow management',
    description: 'Generator platform for creating white-label versions for founders to get investment-ready and investors to manage incoming pitch outreach. Spin up customized versions in days.',
    url: 'https://raiseready-template.vercel.app',
    status: 'live',
    category: 'generators',
    hasVoiceAI: true,
    featured: true,
    type: 'parent',
    isGenerator: true,
    children: ['raiseready-impact'],
  },
  {
    id: 'connexions',
    name: 'Connexions',
    slug: 'connexions',
    tagline: 'AI-powered survey and interview analysis',
    problem: 'Qualitative research is time-consuming and insights get lost',
    description: 'Generator platform for white-label AI voice interviewers with enhanced AI analysis. Conduct customer research, user feedback, exit interviews, and compliance audits - then let AI extract themes, sentiment, and actionable insights from your surveys and research interviews automatically.',
    url: 'https://connexions-silk.vercel.app',
    status: 'live',
    category: 'generators',
    hasVoiceAI: true,
    featured: true,
    type: 'parent',
    isGenerator: true,
    children: ['universal-interviews'],
  },
  // UniversalLingo - Real-time Translation Generator
  {
    id: 'universallingo',
    name: 'UniversalLingo',
    slug: 'universallingo',
    tagline: 'Break language barriers in real-time',
    problem: 'Businesses need scalable multilingual communication',
    description: 'Generator platform for real-time AI translation across industries. One core capability—<1s latency translation in 100+ languages—verticalized into industry-specific products. Spin up white-label translation solutions for tourism, healthcare, government, education, hospitality, and more.',
    url: 'https://universal-lingo-marketing.vercel.app',
    status: 'live',
    category: 'generators',
    hasVoiceAI: true,
    featured: true,
    type: 'parent',
    isGenerator: true,
    children: ['tourlingo', 'govlingo', 'censuslingo', 'videolingo', 'hotellingo', 'doctorlingo', 'edulingo', 'personallingo'],
  },

  // ----------------------------------------
  // VOICE COACHING (Non-Generator Parents)
  // ----------------------------------------

  {
    id: 'kira',
    name: 'Kira',
    slug: 'kira',
    tagline: 'Your personalized AI thinking partner',
    problem: 'Generic AI assistants don\'t know your context and make you repeat yourself',
    description: 'Not one AI for everyone — a unique thinking partner built around YOUR specific goal. Whether it\'s career decisions, financial planning, business strategy, or life changes, Kira learns your context through voice conversation and remembers everything. She asks questions before jumping to answers, pushes back when something\'s unclear, and thinks WITH you instead of just answering.',
    url: 'https://kira-rho.vercel.app',
    status: 'live',
    category: 'voice-coaching',
    hasVoiceAI: true,
    featured: true,
    type: 'parent',
    isGenerator: false,
  },

  // ----------------------------------------
  // BUSINESS TOOLS
  // ----------------------------------------

  {
    id: 'launchready',
    name: 'LaunchReady',
    slug: 'launchready',
    tagline: 'Voice-guided IP protection for founders',
    problem: 'Founders\' IP is vulnerable - 72% have unprotected assets',
    description: 'Protect your ideas before someone else does. Voice-guided IP discovery, automatic evidence capture from GitHub, trademark monitoring, patent deadline tracking, and lawyer-ready packages. Free tier with shared infrastructure, $30/mo for dedicated isolation.',
    url: 'https://launchready-ruby.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: true,
    featured: true,
    type: 'parent',
  },
  {
    id: 'dealfindrs',
    name: 'DealFindrs',
    slug: 'dealfindrs',
    tagline: 'AI-powered property deal assessment',
    problem: 'Property developers waste time on bad deals',
    description: 'Platform for property developers to easily assess deals using AI voice coaches and analysis tools. Fast filtering, smart recommendations, voice-powered deal evaluation.',
    url: 'https://deal-findrs.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: true,
    featured: true,
    type: 'parent',
  },
  {
    id: 'tenderwatch',
    name: 'TenderWatch',
    slug: 'tenderwatch',
    tagline: 'Government tender monitoring made easy',
    problem: 'Australian businesses miss relevant government tenders',
    description: 'Makes monitoring government tenders in Australia easy and convenient. AI-powered matching, automated alerts, never miss a relevant RFP again.',
    url: 'https://tenderwatch-alpha.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },
  {
    id: 'checkpoint',
    name: 'Checkpoint',
    slug: 'checkpoint',
    tagline: 'Modular industry project management',
    problem: 'Generic project tools don\'t fit industry workflows',
    description: 'Modular industry project management and execution platform. Configurable for construction, manufacturing, services - any industry with complex project workflows.',
    url: 'https://f2k-checkpoint-new.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },
  {
    id: 'cleanclose',
    name: 'CleanClose',
    slug: 'cleanclose',
    tagline: 'Help businesses close down cleanly',
    problem: 'Business shutdown is messy and stressful',
    description: 'Platform to help businesses close down cleanly. Compliance checklists, stakeholder communication, asset management, legal requirements - all in one place.',
    url: 'https://corporateaisolutions.com/cleanclosewaitlist/',
    status: 'building',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },
  {
    id: 'f2k-fund-tokenisation',
    name: 'F2K Fund Tokenisation',
    slug: 'f2k-fund-tokenisation',
    tagline: 'Tokenised Australian housing fund on Ethereum',
    problem: 'Property investment is illiquid and inaccessible to many investors',
    description: 'Tokenised Australian housing fund using ERC-3643 security tokens on Ethereum. Wholesale investor onboarding, KYC verification, USDC subscriptions, token minting, NAV publication, and quarterly distributions. Full investor portal and admin console.',
    url: 'https://f2-k-fund-tokenisation.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    featured: true,
    type: 'parent',
  },
  {
    id: 'storyverse',
    name: 'StoryVerse',
    slug: 'storyverse',
    tagline: 'AI-powered personalised children\'s books',
    problem: 'Generic children\'s books don\'t grow with your child',
    description: 'AI-powered personalised children\'s books that evolve from ages 0-18. Story memory that grows with your child, parent voice cloning for narration in your own voice, and an 18-year journey ending with a graduation anthology. Every book is unique.',
    url: 'https://story-verse-two.vercel.app/',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: true,
    featured: true,
    type: 'parent',
  },
  {
    id: 'outreachready',
    name: 'OutreachReady',
    slug: 'outreachready',
    tagline: 'AI-powered strategic outreach with voice coaching',
    problem: 'Cold outreach is generic and ineffective',
    description: 'Strategic outreach platform with voice-guided message crafting, AI personalisation, and multi-channel support across LinkedIn, email, and WhatsApp. Strategic journey framework with funnel stages and relationship goals.',
    url: 'https://outreach-ready.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: true,
    type: 'parent',
  },
  {
    id: 'easyopenclaw',
    name: 'EasyOpenClaw',
    slug: 'easyopenclaw',
    tagline: 'Autonomous AI agent wrapper',
    problem: 'AI agents are powerful but hard to deploy and manage',
    description: 'User-friendly wrapper around the OpenClaw autonomous AI agent. Simple API interface for invoking AI functions, listing capabilities, querying past invocations, and monitoring agent health.',
    url: 'https://gbta-openclaw.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },
  {
    id: 'rnd-tax-tracker',
    name: 'R&D Tax Tracker',
    slug: 'rnd-tax-tracker',
    tagline: 'R&D tax eligibility work recording',
    problem: 'Businesses miss R&D tax credits because they don\'t track eligible work',
    description: 'Platform for recording and tracking work eligible for R&D tax credits. Capture activities, link to eligible categories, and generate compliance-ready documentation for your tax agent.',
    url: 'https://r-and-d-tax-eligibility-work-record.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },
  {
    id: 'ndis-sda-automate',
    name: 'NDIS SDA Automate',
    slug: 'ndis-sda-automate',
    tagline: 'NDIS & SDA compliance automation',
    problem: 'NDIS providers drown in compliance paperwork',
    description: 'Automation platform for NDIS and SDA compliance. Streamline participant documentation, service agreements, reporting requirements, and audit preparation for disability service providers.',
    url: 'https://ndissda-automate.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },
  {
    id: 'longtail-ai-venture-studio',
    name: 'Long Tail AI Venture Studio',
    slug: 'longtail-ai-venture-studio',
    tagline: 'AI venture portfolio dashboard',
    problem: 'Managing multiple AI ventures needs a central command hub',
    description: 'Central dashboard for the Long Tail AI Ventures portfolio. Track venture metrics, Stripe revenue, subscriber targets, and individual venture performance across the entire studio.',
    url: 'https://longtail-ai-venture-studio.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },
  {
    id: 'smartboard',
    name: 'SmartBoard',
    slug: 'smartboard',
    tagline: 'Intelligent airline boarding management',
    problem: 'Gate congestion wastes time and frustrates passengers',
    description: 'Intelligent airline boarding management system that eliminates gate congestion by assigning passengers specific boarding time windows and overhead bin locations based on carry-on luggage and seat number. Self-configuring bin allocation with no airline API required.',
    url: 'https://smart-board-eight.vercel.app/',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },
  {
    id: 'storefront-mcp',
    name: 'Storefront MCP',
    slug: 'storefront-mcp',
    tagline: 'Agent marketplace via MCP protocol',
    problem: 'AI agents can\'t discover and book real-world services',
    description: 'MCP server exposing the Agent Storefront seller catalog as callable tools for any MCP-compatible agent. Agents can search sellers, check availability, and create bookings — bridging AI assistants to real-world service providers.',
    url: 'https://storefront-mcp-eight.vercel.app/',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },
  {
    id: 'easy-claude-code',
    name: 'Easy Claude Code',
    slug: 'easy-claude-code',
    tagline: 'Browser dashboard for Claude Code sessions',
    problem: 'Claude Code terminal sessions are ephemeral — context dies when you close them',
    description: 'Browser dashboard for managing local Claude Code sessions. Session persistence, project tracking, and remote control via Dispatch. Wraps the raw CLI tool in a persistent, context-aware interface with mobile-triggerable workflows.',
    url: 'https://easy-claude-code.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },

  {
    id: 'disaster-support',
    name: 'Disaster Support',
    slug: 'disaster-support',
    tagline: 'Emergency aid and disaster response coordination',
    problem: 'Disaster response is chaotic and poorly coordinated',
    description: 'Emergency aid and disaster response coordination platform with voice capabilities. Connect affected communities with resources, volunteers, and support services in real-time during natural disasters and emergencies.',
    url: 'https://disaster-support.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: true,
    type: 'parent',
  },
  {
    id: 'partner-pilot',
    name: 'PartnerPilot',
    slug: 'partner-pilot',
    tagline: 'AI-powered channel partner discovery',
    problem: 'Finding the right channel partners is time-consuming and hit-or-miss',
    description: 'Helps founders find channel partners, enrich contacts, draft outreach, send emails, and track replies. Five-stage hybrid pipeline with Brave Search, Hunter.io email lookup, Claude AI drafting, and email tracking.',
    url: 'https://partner-pilot.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },
  {
    id: 'investor-pilot',
    name: 'InvestorPilot',
    slug: 'investor-pilot',
    tagline: 'AI-powered investor relations and deal flow',
    problem: 'Founders struggle to manage investor relationships and deal flow effectively',
    description: 'AI-powered investor relations platform. Manage deal flow, track investor conversations, prepare pitch materials, and streamline the fundraising process with intelligent automation.',
    url: 'https://investor-pilot-pi.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },
  {
    id: 'property-services',
    name: 'Property Services',
    slug: 'property-services',
    tagline: 'Shared property intelligence platform',
    problem: 'Property products duplicate data and infrastructure',
    description: 'Shared property intelligence platform powering F2K, DealFindrs, and MMC Build. Supabase edge functions, TypeScript SDK, 20 LGA databases, and QLD Globe integration. One data layer for all property-related ventures.',
    url: 'https://property-services-kappa.vercel.app/',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },
  {
    id: 'mmcbuild',
    name: 'MMC Build',
    slug: 'mmcbuild',
    tagline: 'Modern methods of construction compliance & management',
    problem: 'MMC projects are buried in compliance, drawings, and document chaos',
    description: 'Property compliance and construction management platform for modern methods of construction. 3D visualization, document processing, and project workflows tailored to modular and prefab builds.',
    url: 'https://mmcbuild.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },
  {
    id: 'mova',
    name: 'Mova',
    slug: 'mova',
    tagline: 'Voice-powered multilingual mobility',
    problem: 'Transport providers struggle to serve non-English-speaking riders',
    description: 'AI-powered multi-language mobility and transportation platform. Voice agent handles bookings, navigation, and rider communication in any language — with maps integration and real-time coordination.',
    url: 'https://mova.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: true,
    type: 'parent',
  },
  {
    id: 'lingopure-ai',
    name: 'LingoPure AI',
    slug: 'lingopure-ai',
    tagline: 'AI-first business English platform',
    problem: 'Business English learners need real conversation practice, not textbooks',
    description: 'AI-first business English learning platform with placement assessment, ClassIn integration, and voice agent practice. Students get adaptive lessons and conversation reps with an ElevenLabs-powered tutor.',
    url: 'https://lingo-pure-ai.vercel.app',
    status: 'live',
    category: 'voice-coaching',
    hasVoiceAI: true,
    type: 'parent',
  },
  {
    id: 'hairstylist-ai',
    name: 'HairStylist AI',
    slug: 'hairstylist-ai',
    tagline: 'In-chair AI consultation for stylists',
    problem: 'Clients can\'t visualize a new cut before committing — and stylists lose time on miscommunication',
    description: 'In-chair consultation tool for hair stylists. Take a selfie, generate AI previews of proposed cuts and styles, and align with the client before the first snip. Reduces re-dos and builds confidence in the chair.',
    url: 'https://hair-stylist-ai.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },
  {
    id: 'f2k-offshore-modular',
    name: 'F2K Offshore Modular',
    slug: 'f2k-offshore-modular',
    tagline: 'Pre-vetted offshore modular manufacturer marketplace',
    problem: 'Australian housing buyers can\'t safely source offshore modular manufacturers',
    description: 'Two-sided platform connecting Australian housing buyers with pre-vetted offshore modular manufacturers. Prequalification, compliance verification, and structured deal flow between buyer and factory.',
    url: 'https://f2-k-offshore-modular.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },
  {
    id: 'leadspark',
    name: 'LeadSpark',
    slug: 'leadspark',
    tagline: 'Embeddable AI lead-capture chat widget',
    problem: 'Static contact forms convert poorly and waste warm visitor intent',
    description: 'Multi-tenant lead-capture platform with an embeddable chat widget, voice-enabled qualification, knowledge-base-aware responses, and a tenant portal for lead triage. Drop the widget on any site, capture qualified leads, and route them to your CRM.',
    url: 'https://leadspark-tenant.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: true,
    type: 'parent',
  },
  {
    id: 'omq-outreach',
    name: 'OMQ Outreach',
    slug: 'omq-outreach',
    tagline: 'AI-powered procurement contact discovery and outreach',
    problem: 'Reaching named procurement decision-makers at scale is slow, manual, and brittle',
    description: 'Procurement-focused outreach pipeline: discover named contacts at target organisations via Brave Search and Claude scoring, enrich verified emails through Hunter.io, draft personalised email and LinkedIn copy, send via Resend, and triage replies into a managed cohort queue. Purpose-built for the F2K Offshore Modular Qualified Australian Market Validation campaign.',
    url: 'https://omq-outreach.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },
  {
    id: 'aiftis',
    name: 'AIFTIS Recognition Rail',
    slug: 'aiftis',
    tagline: 'Cross-border professional credential infrastructure for ASEAN MRA signatories',
    problem: 'Professionals face 12–18 months of redundant verification when seeking work across ASEAN borders',
    description: 'Trust infrastructure layer above credentialing providers — enables associations to issue, and regulators to verify, portable professional credentials across ASEAN Mutual Recognition Agreement nations. Cryptographic credential wallets, regulator verification portals, and instant access to portable credentials anchored in regional qualification frameworks. Cuts cross-border verification from 12–18 months to 4–6 weeks while preserving each nation\'s regulatory sovereignty.',
    url: 'https://aiftis-demo.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: false,
    type: 'parent',
  },

  // ============================================
  // CHILD PLATFORMS (White-Label Examples)
  // ============================================

  // ----------------------------------------
  // Children of RaiseReady Template
  // ----------------------------------------

  {
    id: 'raiseready-impact',
    name: 'RaiseReady Impact',
    slug: 'raiseready-impact',
    tagline: 'AI pitch coaching for impact founders',
    problem: 'Impact founders need specialized pitch practice',
    description: 'Live platform for the founder/investor impact sector. Practice pitches with AI investors focused on impact metrics, ESG, and social returns.',
    url: 'https://raiseready-six.vercel.app',
    status: 'live',
    category: 'voice-coaching',
    hasVoiceAI: true,
    type: 'child',
    parentId: 'raiseready-template',
  },

  // ----------------------------------------
  // Children of Connexions
  // ----------------------------------------

  {
    id: 'universal-interviews',
    name: 'Universal Interviews',
    slug: 'universal-interviews',
    tagline: 'AI-powered interview panels',
    problem: 'Scaling customer research interviews',
    description: 'Generated from Connexions. AI interviewer panels for customer research, user feedback, and market validation at scale.',
    url: 'https://universal-interviews.vercel.app',
    status: 'live',
    category: 'voice-coaching',
    hasVoiceAI: true,
    type: 'child',
    parentId: 'connexions',
  },

  // ----------------------------------------
  // Children of UniversalLingo
  // ----------------------------------------

  {
    id: 'tourlingo',
    name: 'TourLingo',
    slug: 'tourlingo',
    tagline: 'Real-time translation for tour groups',
    problem: 'Tour operators struggle with international visitors',
    description: 'Multi-language platform for tourism. Real-time translation, booking management, operator portal. Complete dual-app ecosystem for tour operators and travelers.',
    url: 'https://tour-lingo.vercel.app',
    status: 'live',
    category: 'business-tools',
    hasVoiceAI: true,
    type: 'child',
    parentId: 'universallingo',
  },
  {
    id: 'govlingo',
    name: 'GovLingo',
    slug: 'govlingo',
    tagline: 'Multilingual government service access',
    problem: 'Government services inaccessible to non-English speakers',
    description: 'AI translation platform for government agencies. Enable multilingual access to public services, forms, and citizen communications.',
    url: 'https://universal-lingo-marketing.vercel.app/govlingo',
    status: 'building',
    category: 'business-tools',
    hasVoiceAI: true,
    type: 'child',
    parentId: 'universallingo',
  },
  {
    id: 'censuslingo',
    name: 'CensusLingo',
    slug: 'censuslingo',
    tagline: 'Multilingual census operations support',
    problem: 'Census data collection limited by language barriers',
    description: 'AI translation for large-scale census and survey operations. Enable accurate data collection across all language communities.',
    url: 'https://universal-lingo-marketing.vercel.app/censuslingo',
    status: 'building',
    category: 'business-tools',
    hasVoiceAI: true,
    type: 'child',
    parentId: 'universallingo',
  },
  {
    id: 'videolingo',
    name: 'VideoLingo',
    slug: 'videolingo',
    tagline: 'Real-time translation for video calls',
    problem: 'Remote teams struggle with multilingual communication',
    description: 'AI-powered real-time translation for video conferencing. Break language barriers in Zoom, Teams, and any video platform.',
    url: 'https://universal-lingo-marketing.vercel.app/videolingo',
    status: 'building',
    category: 'business-tools',
    hasVoiceAI: true,
    type: 'child',
    parentId: 'universallingo',
  },
  {
    id: 'hotellingo',
    name: 'HotelLingo',
    slug: 'hotellingo',
    tagline: 'Guest communication for hospitality',
    problem: 'Hotels struggle to serve international guests',
    description: 'AI translation platform for hotels and hospitality. Enable seamless guest communication, concierge services, and room service in any language.',
    url: 'https://universal-lingo-marketing.vercel.app/hotellingo',
    status: 'building',
    category: 'business-tools',
    hasVoiceAI: true,
    type: 'child',
    parentId: 'universallingo',
  },
  {
    id: 'doctorlingo',
    name: 'DoctorLingo',
    slug: 'doctorlingo',
    tagline: 'Medical interpretation made accessible',
    problem: 'Healthcare providers can\'t communicate with non-English patients',
    description: 'AI medical interpretation platform. HIPAA-aware translation for patient consultations, medical history, and care instructions.',
    url: 'https://universal-lingo-marketing.vercel.app/doctorlingo',
    status: 'building',
    category: 'business-tools',
    hasVoiceAI: true,
    type: 'child',
    parentId: 'universallingo',
  },
  {
    id: 'edulingo',
    name: 'EduLingo',
    slug: 'edulingo',
    tagline: 'Classroom translation for inclusive education',
    problem: 'Schools can\'t support non-English speaking students and parents',
    description: 'AI translation for education. Real-time classroom translation, parent-teacher communication, and multilingual learning materials.',
    url: 'https://universal-lingo-marketing.vercel.app/edulingo',
    status: 'building',
    category: 'business-tools',
    hasVoiceAI: true,
    type: 'child',
    parentId: 'universallingo',
  },
  {
    id: 'personallingo',
    name: 'PersonalLingo',
    slug: 'personallingo',
    tagline: 'Your personal interpreter',
    problem: 'Individuals need on-demand translation for daily life',
    description: 'Personal AI interpreter in your pocket. Real-time translation for travel, shopping, appointments, and everyday conversations.',
    url: 'https://universal-lingo-marketing.vercel.app/personallingo',
    status: 'building',
    category: 'business-tools',
    hasVoiceAI: true,
    type: 'child',
    parentId: 'universallingo',
  },
]

// Helper functions
export const getParentPlatforms = () => PLATFORMS.filter(p => p.type === 'parent')
export const getChildPlatforms = () => PLATFORMS.filter(p => p.type === 'child')
export const getGeneratorPlatforms = () => PLATFORMS.filter(p => p.isGenerator)
export const getChildrenOf = (parentId: string) => PLATFORMS.filter(p => p.parentId === parentId)
export const getLivePlatforms = () => PLATFORMS.filter(p => p.status === 'live')
export const getFeaturedPlatforms = () => PLATFORMS.filter(p => p.featured)
export const getVoiceAIPlatforms = () => PLATFORMS.filter(p => p.hasVoiceAI && p.type === 'parent')

// Pricing tiers
export const PRICING_TIERS: PricingTier[] = [
  {
    name: 'Community',
    price: 'Free',
    description: 'Join The Easily Distracted. Share problems, find collaborators.',
    features: [
      'Skool community access',
      'Share problems & ideas',
      'Find potential collaborators',
      'Learn in public',
      'No commitment',
    ],
    cta: {
      label: 'Join Free',
      href: SKOOL.url,
    },
    variant: 'default',
  },
  {
    name: 'Starter',
    price: '$49',
    period: '/mo',
    description: 'Access one platform. Perfect for trying out a specific solution.',
    features: [
      '1 platform access',
      'Unlimited usage',
      'Email support',
      'All future updates',
      'Switch platforms monthly',
    ],
    cta: {
      label: 'Get Started',
      href: '/contact?plan=starter',
    },
    variant: 'default',
  },
  {
    name: 'Pro',
    price: '$199',
    period: '/mo',
    description: 'Full access to all platforms. Best value for power users.',
    features: [
      'All platforms',
      'Unlimited usage',
      'Priority support',
      'Early access to new platforms',
      'API access where available',
      'Custom integrations',
    ],
    cta: {
      label: 'Get Full Access',
      href: '/contact?plan=pro',
    },
    variant: 'featured',
  },
  {
    name: 'Partner',
    price: 'Rev Share',
    description: 'Build something new together. You bring the problem, we build the solution.',
    features: [
      'Custom solution built for you',
      'Ongoing revenue share (10-30%)',
      'Your name on the product',
      'Direct collaboration',
      'Built in days, not months',
      'No upfront cost',
    ],
    cta: {
      label: "Let's Talk",
      href: '/partner',
    },
    variant: 'partner',
  },
]

// Voice Agents - IDs populated by setup:elevenlabs script or env vars
// After running `npm run setup:elevenlabs`, agent IDs will be in env vars or elevenlabs-agents.ts


export const VOICE_AGENTS: Record<string, VoiceAgentConfig> = {
  alex: {
    agentId: process.env.NEXT_PUBLIC_ELEVENLABS_AGENT_ALEX || '',
    name: 'Alex',
    personality: 'Warm and approachable, direct and efficient',
    greeting: `Hey! I'm Alex from Long Tail AI Studio. We're the factory that builds AI companies — ${PLATFORMS.length} platforms and counting. Are you looking to use our existing platforms, or do you have a problem you'd like us to solve?`,
    pageContext: 'homepage',
    gender: 'male',
    canRoute: {
      solutions: true,
      partner: true,
      community: true,
      pricing: true,
    },
  },
   kira: {
     agentId: process.env.NEXT_PUBLIC_ELEVENLABS_AGENT_KIRA || '',
     name: 'Kira',
     personality: 'Thoughtful and direct, a thinking partner not a cheerleader',
     greeting: "Hi, I'm Kira — I help experienced professionals think through their startup ideas. I'm curious about what you're building. What's the problem you want to solve?",
     pageContext: 'launchstack',
     gender: 'female',
     avatar: '/female_avatar.jpeg',
     canRoute: {
       solutions: false,
       partner: true,
       community: false,
        pricing: true,
     },
   },

  scout: {
    agentId: process.env.NEXT_PUBLIC_ELEVENLABS_AGENT_SCOUT || '',
    name: 'Scout',
    personality: 'Curious and helpful, knowledgeable about platforms',
    greeting: `Hi, I'm Scout! I help people find the right AI platform for their needs. We've got ${PLATFORMS.length} to choose from. What kind of problem are you trying to solve?`,
    pageContext: 'marketplace',
    gender: 'female',
    avatar: '/female_avatar.jpeg',
    canRoute: {
      solutions: true,
      partner: true,
      community: false,
      pricing: true,
    },
  },
  morgan: {
    agentId: process.env.NEXT_PUBLIC_ELEVENLABS_AGENT_MORGAN || '',
    name: 'Morgan',
    personality: 'Professional and consultative, deal-savvy',
    greeting: "Hello, I'm Morgan. I handle partnerships, investment inquiries, and team opportunities for the studio. Which of these brings you here today?",
    pageContext: 'business',
    gender: 'female',
    avatar: '/female_avatar.jpeg',
    canRoute: {
      solutions: false,
      partner: true,
      community: true,
      pricing: false,
    },
  },
  victoria: {
    agentId: process.env.NEXT_PUBLIC_ELEVENLABS_AGENT_VICTORIA || '',
    name: 'Victoria',
    personality: 'Refined and professional, efficient at qualification',
    greeting: "Hello, I'm Victoria. I help qualify investment inquiries for the Long Tail AI Studio. Are you exploring investment opportunities with us today?",
    pageContext: 'invest',
    gender: 'female',
    avatar: '/female_avatar.jpeg',
    canRoute: {
      solutions: false,
      partner: true,
      community: true,
      pricing: false,
    },
  },
}

// Default agent when specific agent isn't available
export const DEFAULT_AGENT = 'alex'

// Stats for homepage
export const STATS = [
  { number: String(PLATFORMS.length), label: 'Platforms Built' },
  { number: '72h', label: 'Average Build Time' },
  { number: '35+', label: 'Years Experience' },
]

// Process steps
export const PROCESS_STEPS = [
  {
    number: '01',
    title: 'Learn the Problem',
    description: 'Deep dive into your industry, pain points, and existing workflows. We don\'t build generic solutions—we build YOUR solution.',
    time: 'Day 1',
  },
  {
    number: '02',
    title: 'Define the Solution',
    description: 'Map the user journey, identify AI integration points, and architect a system that actually solves the problem—not just looks good in a demo.',
    time: 'Day 1-2',
  },
  {
    number: '03',
    title: 'Build It Fast',
    description: 'Next.js, Vercel, Supabase, Claude AI, ElevenLabs. Modern stack. Rapid iteration. Working software, not wireframes.',
    time: 'Day 2-4',
  },
  {
    number: '04',
    title: 'Ship & Iterate',
    description: 'Deploy to production. Real users. Real feedback. Continuous improvement. Your solution gets better every day.',
    time: 'Day 5+',
  },
]