/**
 * Client Reviews & Testimonials
 * 
 * This file is AUTO-GENERATED by the review sync system.
 * Do not edit manually - changes will be overwritten.
 * 
 * To update reviews:
 * 1. Submit via website form (/submit-review)
 * 2. Approve in admin panel (/admin/reviews)
 * 3. System auto-updates this file and redeploys
 * 
 * Last updated: [AUTO-GENERATED]
 * Generated by: review-sync-service
 */

export interface ClientReview {
  id: string
  clientName: string
  clientTitle?: string
  clientCompany?: string
  clientPhoto?: string
  clientLinkedIn?: string
  reviewText: string
  rating: 1 | 2 | 3 | 4 | 5
  platformUsed?: string
  featured: boolean
  publishedAt: string
}

// Featured reviews (shown on homepage)
export const FEATURED_REVIEWS: ClientReview[] = [
  // AUTO-GENERATED - Do not edit
  // Example:
  // {
  //   id: 'uuid',
  //   clientName: 'John Smith',
  //   clientTitle: 'CEO',
  //   clientCompany: 'Acme Corp',
  //   clientPhoto: '/images/reviews/john-smith.jpg',
  //   reviewText: 'Corporate AI Solutions transformed our business...',
  //   rating: 5,
  //   platformUsed: 'Rehearsals AI',
  //   featured: true,
  //   publishedAt: '2026-03-28T03:00:00Z'
  // }
]

// All approved reviews
export const ALL_REVIEWS: ClientReview[] = [
  // AUTO-GENERATED - Do not edit
]

// Reviews by platform
export const REVIEWS_BY_PLATFORM: Record<string, ClientReview[]> = {
  // AUTO-GENERATED - Do not edit
}

// Review statistics
export const REVIEW_STATS = {
  total: ALL_REVIEWS.length,
  featured: FEATURED_REVIEWS.length,
  averageRating: ALL_REVIEWS.length > 0 
    ? (ALL_REVIEWS.reduce((sum, r) => sum + r.rating, 0) / ALL_REVIEWS.length).toFixed(1)
    : '0.0',
  fiveStarCount: ALL_REVIEWS.filter(r => r.rating === 5).length,
  lastUpdated: '[AUTO-GENERATED]'
}

// Helper functions
export function getReviewsByPlatform(platformId: string): ClientReview[] {
  return REVIEWS_BY_PLATFORM[platformId] || []
}

export function getFeaturedReviews(limit?: number): ClientReview[] {
  return limit ? FEATURED_REVIEWS.slice(0, limit) : FEATURED_REVIEWS
}

export function getLatestReviews(limit: number = 10): ClientReview[] {
  return [...ALL_REVIEWS]
    .sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime())
    .slice(0, limit)
}
