/**
 * Review Sync Script
 * 
 * Fetches approved reviews from Supabase and updates review-constants.ts
 * 
 * Runs:
 * - Manually: npm run sync-reviews
 * - Automatically: On review approval (via webhook)
 * - Scheduled: Daily via GitHub Actions
 */

import { createClient } from '@supabase/supabase-js'
import * as fs from 'fs'
import * as path from 'path'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY! // Use service role for full access
)

interface Review {
  id: string
  client_name: string
  client_title: string | null
  client_company: string | null
  client_photo_url: string | null
  client_linkedin_url: string | null
  review_text: string
  rating: number
  platform_used: string | null
  featured: boolean
  published_at: string
}

async function syncReviews() {
  console.log('🔄 Syncing reviews from Supabase...')
  
  try {
    // Fetch all approved & published reviews
    const { data: reviews, error } = await supabase
      .from('client_reviews')
      .select('*')
      .eq('status', 'approved')
      .eq('published', true)
      .order('display_order', { ascending: true })
      .order('published_at', { ascending: false })
    
    if (error) {
      throw error
    }
    
    console.log(`✅ Found ${reviews.length} approved reviews`)
    
    // Transform to constants format
    const allReviews = reviews.map(transformReview)
    const featuredReviews = reviews.filter(r => r.featured).map(transformReview)
    
    // Group by platform
    const reviewsByPlatform: Record<string, any[]> = {}
    reviews.forEach(review => {
      if (review.platform_used) {
        if (!reviewsByPlatform[review.platform_used]) {
          reviewsByPlatform[review.platform_used] = []
        }
        reviewsByPlatform[review.platform_used].push(transformReview(review))
      }
    })
    
    // Generate TypeScript file
    const fileContent = generateConstantsFile(allReviews, featuredReviews, reviewsByPlatform)
    
    // Write to file
    const filePath = path.join(process.cwd(), 'src', 'lib', 'review-constants.ts')
    fs.writeFileSync(filePath, fileContent, 'utf-8')
    
    console.log(`✅ Updated ${filePath}`)
    console.log(`   - ${allReviews.length} total reviews`)
    console.log(`   - ${featuredReviews.length} featured`)
    console.log(`   - ${Object.keys(reviewsByPlatform).length} platforms`)
    
    // Commit and push (if running in CI/CD)
    if (process.env.CI) {
      await commitAndPush()
    }
    
  } catch (error) {
    console.error('❌ Sync failed:', error)
    process.exit(1)
  }
}

function transformReview(review: Review) {
  return {
    id: review.id,
    clientName: review.client_name,
    clientTitle: review.client_title || undefined,
    clientCompany: review.client_company || undefined,
    clientPhoto: review.client_photo_url || undefined,
    clientLinkedIn: review.client_linkedin_url || undefined,
    reviewText: review.review_text,
    rating: review.rating as 1 | 2 | 3 | 4 | 5,
    platformUsed: review.platform_used || undefined,
    featured: review.featured,
    publishedAt: review.published_at
  }
}

function generateConstantsFile(
  allReviews: any[],
  featuredReviews: any[],
  reviewsByPlatform: Record<string, any[]>
): string {
  const now = new Date().toISOString()
  const avgRating = allReviews.length > 0
    ? (allReviews.reduce((sum, r) => sum + r.rating, 0) / allReviews.length).toFixed(1)
    : '0.0'
  
  return `/**
 * Client Reviews & Testimonials
 * 
 * This file is AUTO-GENERATED by the review sync system.
 * Do not edit manually - changes will be overwritten.
 * 
 * To update reviews:
 * 1. Submit via website form (/submit-review)
 * 2. Approve in admin panel (/admin/reviews)
 * 3. Run: npm run sync-reviews
 * 4. Deploy to production
 * 
 * Last updated: ${now}
 * Generated by: review-sync-service
 * Reviews: ${allReviews.length} total, ${featuredReviews.length} featured
 */

export interface ClientReview {
  id: string
  clientName: string
  clientTitle?: string
  clientCompany?: string
  clientPhoto?: string
  clientLinkedIn?: string
  reviewText: string
  rating: 1 | 2 | 3 | 4 | 5
  platformUsed?: string
  featured: boolean
  publishedAt: string
}

// Featured reviews (shown on homepage)
export const FEATURED_REVIEWS: ClientReview[] = ${JSON.stringify(featuredReviews, null, 2)}

// All approved reviews
export const ALL_REVIEWS: ClientReview[] = ${JSON.stringify(allReviews, null, 2)}

// Reviews by platform
export const REVIEWS_BY_PLATFORM: Record<string, ClientReview[]> = ${JSON.stringify(reviewsByPlatform, null, 2)}

// Review statistics
export const REVIEW_STATS = {
  total: ${allReviews.length},
  featured: ${featuredReviews.length},
  averageRating: '${avgRating}',
  fiveStarCount: ${allReviews.filter(r => r.rating === 5).length},
  lastUpdated: '${now}'
}

// Helper functions
export function getReviewsByPlatform(platformId: string): ClientReview[] {
  return REVIEWS_BY_PLATFORM[platformId] || []
}

export function getFeaturedReviews(limit?: number): ClientReview[] {
  return limit ? FEATURED_REVIEWS.slice(0, limit) : FEATURED_REVIEWS
}

export function getLatestReviews(limit: number = 10): ClientReview[] {
  return [...ALL_REVIEWS]
    .sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime())
    .slice(0, limit)
}
`
}

async function commitAndPush() {
  const { exec } = require('child_process')
  const { promisify } = require('util')
  const execAsync = promisify(exec)
  
  try {
    await execAsync('git add src/lib/review-constants.ts')
    await execAsync('git commit -m "chore: update client reviews [auto-sync]"')
    await execAsync('git push origin main')
    console.log('✅ Committed and pushed to Git')
  } catch (error) {
    console.error('⚠️  Git commit failed:', error)
    // Don't fail the sync if git fails
  }
}

// Run if called directly
if (require.main === module) {
  syncReviews()
}

export { syncReviews }
