-- Gate-readiness fold-in — the ratified GATE_READINESS_REVIEW_V4 workbook becomes
-- machine-applied policy in the cockpit (BUSINESS_MODEL.md §5 rubric discipline,
-- extended to thin-MVP / Gate-1 readiness).
--
-- Two tables:
--   readiness_criteria  : the 45-check catalogue (List 4) — code, tier, weight,
--                         method, relevance. The HARD checks block the Gate-1
--                         Launch button; WEIGHTED checks feed the GO/REDESIGN score.
--   promise_attributes  : per-product "X, not Y" quality bars (List 3) — the
--                         "I want that" definition that scores check #9 per card.
--
-- Seed is auto-generated by cais-shared-services/gate-readiness/extract_workbook.py
-- from the signed-off workbook (single source of truth). Both tables are
-- admin-surface-only: RLS on, no anon policies, accessed via the service role
-- (same posture as methodology_hypothesis_cards). Additive + idempotent.

-- ---------------------------------------------------------------------------
-- readiness_criteria — the ratified check catalogue
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS readiness_criteria (
    code        TEXT PRIMARY KEY,          -- P1..P4 (preconditions), 1..41 (checks)
    check_label TEXT NOT NULL,
    source      TEXT,                       -- BizModel §4 / PS §1 / VMS / THIN / Rule 15 ...
    method      TEXT,                       -- AUTO | NAIVE | VOICE | JUDGE (and slashed combos)
    relevance   TEXT,                       -- IN | PRE | SEC | COND | SCALE | IN-core
    tier        TEXT NOT NULL
        CHECK (tier IN (
            'HARD',                 -- blocks the Gate-1 Launch button
            'CONDITIONAL-HARD',     -- HARD only when that feature exists (auth/voice/IP/...)
            'WEIGHTED',             -- feeds the GO/REDESIGN score (waivable)
            'CONDITIONAL-WEIGHTED', -- weighted only when that feature exists
            'TOO-MUCH',             -- inverse guard: presence pre-GO is itself a flag
            'DEFER'                 -- scale-infra; not scored at Gate 1
        )),
    weight      TEXT CHECK (weight IS NULL OR weight IN ('High', 'Med', 'Low')),
    notes       TEXT,
    sort_order  INT NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ DEFAULT NOW(),
    updated_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_readiness_criteria_tier ON readiness_criteria(tier);
CREATE INDEX IF NOT EXISTS idx_readiness_criteria_sort ON readiness_criteria(sort_order);

ALTER TABLE readiness_criteria ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- promise_attributes — the per-product "I want that" quality bars
-- product_slug matches methodology_hypothesis_cards.product_slug (constants.ts slug).
-- Not a hard FK: a promise bar can be ratified before the card row is seeded.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS promise_attributes (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    product_slug TEXT NOT NULL,
    promise      TEXT,                      -- the Stage-0 one-line promise
    distributor  TEXT,                      -- named distributor archetype (Rule 15)
    attribute    TEXT NOT NULL,             -- the promise piece
    quality_bar  TEXT NOT NULL,             -- ratified "X, not Y" bar
    verify       TEXT,                      -- NAIVE/JUDGE/VOICE/AUTO verification method
    sort_order   INT NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (product_slug, attribute)
);

CREATE INDEX IF NOT EXISTS idx_promise_attributes_slug ON promise_attributes(product_slug);

ALTER TABLE promise_attributes ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- updated_at triggers — reuse the methodology trigger function
-- ---------------------------------------------------------------------------
DROP TRIGGER IF EXISTS readiness_criteria_updated_at ON readiness_criteria;
CREATE TRIGGER readiness_criteria_updated_at
  BEFORE UPDATE ON readiness_criteria
  FOR EACH ROW EXECUTE FUNCTION set_methodology_cards_updated_at();

DROP TRIGGER IF EXISTS promise_attributes_updated_at ON promise_attributes;
CREATE TRIGGER promise_attributes_updated_at
  BEFORE UPDATE ON promise_attributes
  FOR EACH ROW EXECUTE FUNCTION set_methodology_cards_updated_at();

-- ---------------------------------------------------------------------------
-- Seed (auto-generated — see header). Idempotent UPSERTs.
-- ---------------------------------------------------------------------------
-- readiness_criteria: the ratified 45-check catalogue (List 4).
INSERT INTO readiness_criteria
  (code, check_label, source, method, relevance, tier, weight, notes, sort_order)
VALUES
  ('P1', 'MVP link live (HTTP 200)', 'BizModel §4', 'AUTO', 'PRE', 'HARD', NULL, 'HARD - no live link, no Gate-1 outreach send. Non-negotiable.', 0),
  ('P2', 'Named distributor archetype on the card (not ''SMBs'')', 'Rule 15', 'JUDGE', 'PRE', 'HARD', NULL, 'HARD - Rule 15. "SMBs" on a card is itself a Gate-1 failure.', 1),
  ('P3', 'Four gate questions answered non-hand-wavily', 'BizModel §3', 'JUDGE', 'PRE', 'HARD', NULL, 'HARD - the four questions are the BizModel gate; hand-waving = redesign.', 2),
  ('P4', '''Too much'' guard — scale-infra ABSENT pre-GO', 'THIN', 'AUTO/JUDGE', 'PRE', 'TOO-MUCH', NULL, 'TOO-MUCH - team admin / billing / settings pre-GO = over-build flag.', 3),
  ('1', 'Explanatory header (what/do/why) + empty states', 'PS §5', 'NAIVE/JUDGE', 'IN', 'WEIGHTED', 'Med', 'Empty states matter; header sells the concept on landing.', 4),
  ('2', 'Responsive 375 + 1440, no h-scroll, thumb', 'PS §1', 'NAIVE/AUTO', 'IN', 'HARD', NULL, 'HARD - mobile-broken at 375 fails the naive-tester test outright.', 5),
  ('3', 'Touch >=44px, text >=16px, tables mobile strategy', 'PS §1', 'NAIVE', 'IN', 'WEIGHTED', 'High', 'Mobile-first portfolio - thumb-reachable is core DNA, lean HIGH.', 6),
  ('4', 'Nav collapses to drawer/hamburger on mobile', 'PS §1', 'NAIVE', 'IN', 'WEIGHTED', 'Med', 'Drawer/hamburger - common pattern, weight medium.', 7),
  ('5', 'Landing page sells the concept', 'THIN §3', 'NAIVE/JUDGE', 'IN', 'WEIGHTED', 'High', 'Landing-sells = the "I want that" before login. HIGH for distributor-led GTM.', 8),
  ('6', 'Emotional register matches product (not dull shell)', 'PS §9', 'NAIVE/JUDGE', 'IN', 'WEIGHTED', 'High', 'Dull-shell failure is the Singify lesson - HIGH; emotional register is the moat.', 9),
  ('7', 'Browser <title> = product name (not ''Create Next App'')', 'PS §7', 'AUTO', 'IN', 'HARD', NULL, 'HARD - default Next.js title is the most preventable trust-killer.', 10),
  ('8', 'OG image + manifest favicon', 'PS §7', 'AUTO', 'SCALE', 'DEFER', NULL, 'DEFER - polish; do post-Gate-2.', 11),
  ('9', 'PROMISE ATTRIBUTES present AND at quality bar', 'THIN §2/§3', 'JUDGE', 'IN-core', 'WEIGHTED', 'High', 'THE central check - this is the THIN MVP test. HIGH.', 12),
  ('10', 'Voice agent reachable from chrome <=3 clicks', 'PS §6', 'VOICE/NAIVE', 'IN', 'CONDITIONAL-HARD', NULL, 'CONDITIONAL-HARD - portfolio voice DNA; if voiced, must be reachable.', 13),
  ('11', 'Voice consumes @caistech/elevenlabs-convai + /react, BYOK, persona', 'PS §6', 'VOICE/grep', 'COND', 'CONDITIONAL-HARD', NULL, 'CONDITIONAL-HARD - @caistech-first; BYOK is the distribution model.', 14),
  ('12', 'Voice proactive + stage-aware', 'PS §6', 'VOICE live', 'IN', 'WEIGHTED', 'High', 'Stage-aware = the proactive moment; HIGH where voice exists.', 15),
  ('13', 'Voice placement: every Required surface voiced', 'voice-auditor', 'VOICE', 'IN/COND', 'CONDITIONAL-HARD', NULL, 'CONDITIONAL-HARD - voice-auditor is the codified test.', 16),
  ('14', 'Voice memory loop WORKS (welcome-back recall fires, observable)', 'VMS 1-2,13,16', 'VOICE behavioural', 'IN', 'CONDITIONAL-HARD', NULL, 'CONDITIONAL-HARD - welcome-back recall is the memory promise landing.', 17),
  ('15', 'Memory: pull-not-push, distil-then-recall, works off results', 'VMS 3-6', 'grep/JUDGE', 'COND', 'CONDITIONAL-WEIGHTED', 'High', 'Pull-not-push pattern is core IP - HIGH where memory is in scope.', 18),
  ('16', 'Identity server-derived (conversation_id, never user_id)', 'VMS 9', 'grep', 'SEC', 'CONDITIONAL-HARD', NULL, 'CONDITIONAL-HARD (SEC) - identity confusion = data leakage.', 19),
  ('17', 'Every convai webhook verifies HMAC (.trim), unverified->401', 'VMS 10/PS §6', 'grep/AUTO', 'SEC', 'CONDITIONAL-HARD', NULL, 'CONDITIONAL-HARD (SEC) - unverified webhook = pwned.', 20),
  ('18', 'Allowlist on every public agent', 'VMS 18/PS §6', 'AUTO getAgent', 'SEC', 'CONDITIONAL-HARD', NULL, 'CONDITIONAL-HARD (SEC) - public agent = abused agent without allowlist.', 21),
  ('19', 'Workspace-bind webhook (not deprecated per-agent shape)', 'VMS 18/PS §6', 'grep/AUTO', 'SEC', 'CONDITIONAL-HARD', NULL, 'CONDITIONAL-HARD (SEC) - deprecated shape silently breaks.', 22),
  ('20', 'Cross-session authed-only; pre-auth = founder-hardcoded user_id', 'VMS 11', 'grep', 'COND', 'CONDITIONAL-WEIGHTED', 'Med', 'Founder-hardcoded id pre-auth is fine; promote later.', 23),
  ('21', 'Memory owned/deletable/TTL + user memory surface', 'VMS 12', 'JUDGE', 'SCALE', 'DEFER', NULL, 'DEFER - GDPR-style surface; post-Gate-2.', 24),
  ('22', 'Forgot-password link + working reset flow', 'PS §2', 'NAIVE/AUTO', 'COND', 'CONDITIONAL-HARD', NULL, 'CONDITIONAL-HARD - missing reset = blocked user, blocked outreach.', 25),
  ('23', 'Password visibility toggle (shared component)', 'PS §2', 'NAIVE', 'COND', 'CONDITIONAL-HARD', NULL, 'CONDITIONAL-HARD - basic UX; ship shared component.', 26),
  ('24', 'Working magic-link', 'PS §2', 'NAIVE', 'COND', 'CONDITIONAL-HARD', NULL, 'CONDITIONAL-HARD - magic-link is the friction-free path.', 27),
  ('25', 'Auth smoke-test: signup/login/reset/magic-link execute', 'PS §3', 'AUTO/NAIVE', 'COND', 'CONDITIONAL-HARD', NULL, 'CONDITIONAL-HARD - the smoke test = the auth gate.', 28),
  ('26', 'Persistent left navbar on authed routes + active indicator', 'PS §4', 'NAIVE', 'IN', 'WEIGHTED', 'Med', 'Active indicator = orientation; medium weight.', 29),
  ('27', '/settings Profile/Password/Notifications/Account', 'PS §4', 'NAIVE', 'SCALE', 'DEFER', NULL, 'DEFER - full settings surface post-Gate-2.', 30),
  ('28', 'profiles table + on_auth_user_created + RLS', 'PS §4', 'grep/SQL', 'SCALE', 'DEFER', NULL, 'DEFER - data layer can lag; trigger on first auth product.', 31),
  ('29', 'Sign Out present', 'PS §4', 'NAIVE', 'IN', 'CONDITIONAL-WEIGHTED', 'Med', 'Sign Out absence is a tell - medium weight where auth exists.', 32),
  ('30', 'Team admin: orgs/members/roles/invite/usage, /admin', 'PS §8', 'grep/SQL', 'SCALE', 'DEFER', NULL, 'DEFER - team admin = TOO-MUCH pre-GO; aligns with P4.', 33),
  ('31', 'Consequence clarity on irreversible/cost/outreach + confirm', 'PS §0/§9', 'NAIVE', 'IN', 'WEIGHTED', 'High', 'Irreversible/cost/outreach without confirm = trust-killer. HIGH.', 34),
  ('32', 'Zero dead ends — every screen makes next action obvious', 'PS §9', 'NAIVE', 'IN', 'WEIGHTED', 'High', 'Dead ends = exit signal. HIGH for naive-tester pass.', 35),
  ('33', 'Content/IP acknowledgment (/terms + gate) where 3rd-party IP', 'PS §9', 'NAIVE', 'IN', 'CONDITIONAL-HARD', NULL, 'CONDITIONAL-HARD - IP acknowledgment where third-party content exists.', 36),
  ('34', 'Address->Mapbox; company/ABN->ABN lookup', 'PS §9', 'NAIVE', 'COND', 'CONDITIONAL-WEIGHTED', 'Med', 'Mapbox + ABN lookups are the AU-context expectation. Medium.', 37),
  ('35', 'Email sender = updates.corporateaisolutions.com', 'PS §9', 'grep', 'SEC', 'CONDITIONAL-WEIGHTED', 'Med', 'Sender domain consistency = inbox placement; medium weight.', 38),
  ('36', '@caistech-first (fork-check clean)', 'PS §9', 'AUTO', 'SEC', 'WEIGHTED', 'High', '@caistech-first compounds across portfolio. HIGH.', 39),
  ('37', 'Feature pre-flight manifest + preflight run', 'PS §9', 'AUTO', 'PRE', 'WEIGHTED', 'High', 'Preflight = the gate orchestrator; HIGH for build discipline.', 40),
  ('38', 'Supabase: idempotent migrations via CLI, RLS every table, no client service-key', 'PS §9', 'grep/SQL', 'SEC', 'CONDITIONAL-HARD', NULL, 'CONDITIONAL-HARD (SEC) - RLS + no client service-key is non-negotiable.', 41),
  ('39', 'No secrets in committed files / logs', 'PS §9', 'AUTO', 'SEC', 'HARD', NULL, 'HARD (SEC) - secret leak = portfolio-wide breach risk.', 42),
  ('40', 'Vercel env vars sensitive, prod+preview only', 'PS §9', 'AUTO', 'SEC', 'HARD', NULL, 'HARD (SEC) - env hygiene; Vercel default exposes too easily.', 43),
  ('41', 'Human walkthrough: friction/terminology/''I want that''', 'naive-tester', 'NAIVE', 'IN', 'WEIGHTED', 'High', 'Naive-tester walkthrough = the codified "I want that" check. HIGH.', 44)
ON CONFLICT (code) DO UPDATE SET
  check_label = EXCLUDED.check_label, source = EXCLUDED.source,
  method = EXCLUDED.method, relevance = EXCLUDED.relevance,
  tier = EXCLUDED.tier, weight = EXCLUDED.weight,
  notes = EXCLUDED.notes, sort_order = EXCLUDED.sort_order;

-- promise_attributes: the per-product 'X, not Y' quality bars (List 3),
-- only the products whose bars are ratified (bars_filled > 0).
INSERT INTO promise_attributes
  (product_slug, promise, distributor, attribute, quality_bar, verify, sort_order)
VALUES
  ('singify', 'Karaoke on camera with real in-ear backing, pitch-corrected into your own key, coached by an AI that knows your voice', 'Singing teachers & academies', 'Karaoke / sing-along', 'real backing audible IN-EAR with vocal clearly on top, latency under ~60ms - not noticeable lag or speaker bleed', 'NAIVE/JUDGE', 0),
  ('singify', 'Karaoke on camera with real in-ear backing, pitch-corrected into your own key, coached by an AI that knows your voice', 'Singing teachers & academies', 'Vocal polish', 'untrained-ear listener says "wow" on first playback (the share-trigger moment) - not "that sounds better"', 'NAIVE/JUDGE', 1),
  ('singify', 'Karaoke on camera with real in-ear backing, pitch-corrected into your own key, coached by an AI that knows your voice', 'Singing teachers & academies', 'Voice coach', 'voice agent initiates the next coaching step proactively - not waits to be asked', 'NAIVE/JUDGE', 2),
  ('singify', 'Karaoke on camera with real in-ear backing, pitch-corrected into your own key, coached by an AI that knows your voice', 'Singing teachers & academies', '''Knows your voice''', 'agent references a specific prior session detail in turn one ("last time your bridge was flat") - not just "welcome back"', 'NAIVE/JUDGE', 3),
  ('singify', 'Karaoke on camera with real in-ear backing, pitch-corrected into your own key, coached by an AI that knows your voice', 'Singing teachers & academies', 'See yourself', 'video record + playback in one tab, no extra setup - not external camera app', 'NAIVE/JUDGE', 4),
  ('singify', 'Karaoke on camera with real in-ear backing, pitch-corrected into your own key, coached by an AI that knows your voice', 'Singing teachers & academies', 'Distributor pull', 'studio dashboard shows per-student improvement curve + share-back to teacher - not just usage stats', 'JUDGE', 5),
  ('connexions', 'White-label AI voice interviewer that runs adaptive conversations and returns structured insight - not raw transcripts', 'Research & CX firms, recruiters, compliance auditors', 'Voice interviewer', 'interviewee interrupts/redirects and the agent adapts mid-sentence - not a fixed script that resumes', 'NAIVE/JUDGE', 0),
  ('connexions', 'White-label AI voice interviewer that runs adaptive conversations and returns structured insight - not raw transcripts', 'Research & CX firms, recruiters, compliance auditors', 'Insight capture', 'output includes themes + supporting quotes + confidence per theme - not just bullet list of themes', 'NAIVE/JUDGE', 1),
  ('connexions', 'White-label AI voice interviewer that runs adaptive conversations and returns structured insight - not raw transcripts', 'Research & CX firms, recruiters, compliance auditors', 'White-label', 'distributor logo, domain, voice persona configurable end-to-end with zero Connexions branding visible - not "powered by"', 'NAIVE/JUDGE', 2),
  ('connexions', 'White-label AI voice interviewer that runs adaptive conversations and returns structured insight - not raw transcripts', 'Research & CX firms, recruiters, compliance auditors', 'Scale at quality', 'demonstrated run of 100+ interviews same day with consistent insight schema - not a small-N pilot', 'JUDGE', 3),
  ('kira', 'A patient AI companion that guides you through learning a skill, planning a project, or mastering anything; each Kira is personalised', 'Coaching, wellness & education platforms', 'Patient companion (voice)', 'agent waits, asks clarifying follow-ups, accepts long pauses - not a fast-turn chat cadence', 'NAIVE/JUDGE', 0),
  ('kira', 'A patient AI companion that guides you through learning a skill, planning a project, or mastering anything; each Kira is personalised', 'Coaching, wellness & education platforms', 'Remembers + personalises', 'session-1 setup is referenced in session-3 turn-1 without prompting - not generic small-talk recall', 'NAIVE/JUDGE', 1),
  ('kira', 'A patient AI companion that guides you through learning a skill, planning a project, or mastering anything; each Kira is personalised', 'Coaching, wellness & education platforms', 'Each Kira is yours', 'distributor picks name, persona, scope; their members see "Their Kira", not "Kira by CAIS" - not surface-level skin', 'NAIVE/JUDGE', 2),
  ('kira', 'A patient AI companion that guides you through learning a skill, planning a project, or mastering anything; each Kira is personalised', 'Coaching, wellness & education platforms', 'Cross-domain (skill / project / mastery)', 'one continuous thread spans skill + project + mastery for the same user - not three menu options', 'NAIVE/JUDGE', 3),
  ('raiseready-template', 'White-label AI pitch-rehearsal coach - founders practise the raise out loud, get scored, and improve', 'VC accelerators & incubators', 'Pitch rehearsal', 'founder speaks for ≥60s uninterrupted, system catches at least 3 specific delivery issues - not "good rehearsal"', 'NAIVE/JUDGE', 0),
  ('raiseready-template', 'White-label AI pitch-rehearsal coach - founders practise the raise out loud, get scored, and improve', 'VC accelerators & incubators', 'Coaching', 'feedback timestamped to the second + names the issue ("0:43 you said ''um'' 4 times in 10s") - not paragraph summary', 'NAIVE/JUDGE', 1),
  ('raiseready-template', 'White-label AI pitch-rehearsal coach - founders practise the raise out loud, get scored, and improve', 'VC accelerators & incubators', 'Knows your pitch', 'system quotes founder''s own slide 4 in its critique - not generic pitch advice', 'NAIVE/JUDGE', 2),
  ('raiseready-template', 'White-label AI pitch-rehearsal coach - founders practise the raise out loud, get scored, and improve', 'VC accelerators & incubators', 'Cohort/program impact', 'accelerator dashboard shows cohort-level Δ score from rehearsal 1 → rehearsal 5 - not founder-by-founder PDFs', 'JUDGE', 3),
  ('raiseready-template', 'White-label AI pitch-rehearsal coach - founders practise the raise out loud, get scored, and improve', 'VC accelerators & incubators', 'White-label', 'accelerator domain, logo, persona, custom rubrics; founders never see "RaiseReady" - not co-branded header', 'NAIVE/JUDGE', 4),
  ('lingopure-ai', 'Voice-led English/language upskilling with gap-scored micro-learning and CEFR certification; employer cohort dashboards', 'Employers & language schools', 'Gap detection', 'AI names the specific gap (e.g. "your /θ/ becomes /t/ in word-initial position") - not "work on pronunciation"', 'NAIVE/JUDGE', 0),
  ('lingopure-ai', 'Voice-led English/language upskilling with gap-scored micro-learning and CEFR certification; employer cohort dashboards', 'Employers & language schools', 'Micro-learning targeted to gap', 'next exercise drills the named gap specifically + retest closes it - not next-lesson-in-sequence', 'NAIVE/JUDGE', 1),
  ('lingopure-ai', 'Voice-led English/language upskilling with gap-scored micro-learning and CEFR certification; employer cohort dashboards', 'Employers & language schools', 'CEFR certification', 'cert is mapped to CEFR descriptors with auditable evidence per descriptor - not a number + a badge', 'JUDGE', 2),
  ('lingopure-ai', 'Voice-led English/language upskilling with gap-scored micro-learning and CEFR certification; employer cohort dashboards', 'Employers & language schools', 'Cohort dashboard', 'employer sees individual CEFR delta over time + can export proof for compliance - not aggregate score only', 'NAIVE/JUDGE', 3),
  ('dealfindrs', 'AI property-deal assessment - instant Green/Amber/Red on every opportunity', 'Buyers'' agents & property firms', 'Instant verdict', 'G/A/R verdict + headline reason renders in <3s p95 on a fresh deal - not a 30-second processing wait', 'NAIVE/AUTO', 0),
  ('dealfindrs', 'AI property-deal assessment - instant Green/Amber/Red on every opportunity', 'Buyers'' agents & property firms', 'The ''why''', 'the "why" cites the specific metric thresholds breached/met (yield, comparable, planning risk) - not a paragraph of prose', 'NAIVE/JUDGE', 1),
  ('dealfindrs', 'AI property-deal assessment - instant Green/Amber/Red on every opportunity', 'Buyers'' agents & property firms', 'Coverage', 'tested live on 5 unrelated deal types (resi, commercial, off-market, dev site, regional) without breaking - not "works on most"', 'JUDGE', 2),
  ('dealfindrs', 'AI property-deal assessment - instant Green/Amber/Red on every opportunity', 'Buyers'' agents & property firms', 'Distributor edge', 'agent''s client portal shows the agent''s curated G/A/R deals - not a link out to dealfindrs.com', 'JUDGE', 3),
  ('investor-pilot', 'Multi-channel direct outreach - discover, score, draft, approve, send across LinkedIn + email; compliance-aware, audit-logged', 'VC & advisory firms', 'Discover + score', 'each contact card shows ≥3 signal-based reasons ("they led the last 2 rounds in your sector at your stage") - not a fit %', 'NAIVE/JUDGE', 0),
  ('investor-pilot', 'Multi-channel direct outreach - discover, score, draft, approve, send across LinkedIn + email; compliance-aware, audit-logged', 'VC & advisory firms', 'Draft personalised', 'first sentence of draft names the specific shared signal - not "Hi, I saw your work and..."', 'NAIVE/JUDGE', 1),
  ('investor-pilot', 'Multi-channel direct outreach - discover, score, draft, approve, send across LinkedIn + email; compliance-aware, audit-logged', 'VC & advisory firms', 'Approve before send', 'send is blocked until human ticks approve + edits visible since last approval - not a "review then send" toast', 'NAIVE/AUTO', 2),
  ('investor-pilot', 'Multi-channel direct outreach - discover, score, draft, approve, send across LinkedIn + email; compliance-aware, audit-logged', 'VC & advisory firms', 'Multi-channel: LinkedIn + email', 'one send action goes out across both channels with channel-appropriate phrasing - not the same copy on both', 'NAIVE/JUDGE', 3),
  ('investor-pilot', 'Multi-channel direct outreach - discover, score, draft, approve, send across LinkedIn + email; compliance-aware, audit-logged', 'VC & advisory firms', 'Compliance-aware + audit-logged', 'audit log captures sender, recipient, content hash, approval timestamp, consent basis - not just sent/not-sent', 'AUTO/JUDGE', 4),
  ('investor-pilot', 'Multi-channel direct outreach - discover, score, draft, approve, send across LinkedIn + email; compliance-aware, audit-logged', 'VC & advisory firms', 'Warm pipeline feel', 'founder can name 3 reasons they''re messaging this person before sending - not "you generated 50 contacts"', 'JUDGE', 5),
  ('partner-pilot', 'Discovers, scores, and preps outreach for ideal channel partners from an ICP', 'Agencies & BD-as-a-service', 'Partner discovery from ICP', 'ICP is captured before search runs (no defaults), and unmatched results explain WHY they didn''t match - not silent filtering', 'NAIVE/JUDGE', 0),
  ('partner-pilot', 'Discovers, scores, and preps outreach for ideal channel partners from an ICP', 'Agencies & BD-as-a-service', 'The ''why each partner fits''', 'rationale names what the partner brings that you can''t deliver today (capability, channel, geography) - not industry/size match', 'NAIVE/JUDGE', 1),
  ('partner-pilot', 'Discovers, scores, and preps outreach for ideal channel partners from an ICP', 'Agencies & BD-as-a-service', 'Outreach drafted', 'first paragraph references the specific capability gap - not "We help SaaS companies grow"', 'NAIVE/JUDGE', 2),
  ('partner-pilot', 'Discovers, scores, and preps outreach for ideal channel partners from an ICP', 'Agencies & BD-as-a-service', 'Productised BD across clients', 'one agency runs ≥10 distinct client ICPs in parallel without cross-contamination - not "supports multiple users"', 'JUDGE', 3),
  ('partner-pilot', 'Discovers, scores, and preps outreach for ideal channel partners from an ICP', 'Agencies & BD-as-a-service', 'Upstream ICP stages (on horizon)', 'ICP Discovery + Prioritisation + Partner ICP Derivation are visible stages BEFORE search runs - not search-first', 'NAIVE/JUDGE', 4),
  ('ndis-sda-automate', 'Automates NDIS SDA claims, reconciliation, and property management', 'NDIS providers & SDA consultants', 'Claims automation', 'submission-ready claim file generated end-to-end from raw inputs - not a pre-filled form to finish manually', 'NAIVE/JUDGE', 0),
  ('ndis-sda-automate', 'Automates NDIS SDA claims, reconciliation, and property management', 'NDIS providers & SDA consultants', 'Reconciliation', 'reconciliation flags every payment-vs-claim gap with line-item evidence - not a totals mismatch', 'NAIVE/JUDGE', 1),
  ('ndis-sda-automate', 'Automates NDIS SDA claims, reconciliation, and property management', 'NDIS providers & SDA consultants', 'Property management', 'property record shows participants, claims, compliance state, next-action - not a separate property table', 'NAIVE/JUDGE', 2),
  ('ndis-sda-automate', 'Automates NDIS SDA claims, reconciliation, and property management', 'NDIS providers & SDA consultants', 'Auditable', 'each finding shows the NDIS rule reference + the source record (form, invoice, plan) - not "compliant: yes"', 'JUDGE', 3),
  ('ndis-sda-automate', 'Automates NDIS SDA claims, reconciliation, and property management', 'NDIS providers & SDA consultants', 'Capacity unlocked', 'provider takes on ≥1 new participant without adding admin headcount - measurable, not anecdotal', 'JUDGE', 4),
  ('rnd-tax-tracker', 'Captures eligible R&D work as it happens and preps the tax-incentive claim', 'Accountancy firms', 'Capture-as-you-go', 'work captured passively during the activity (commit, doc, meeting) - not a "remember to log" prompt', 'NAIVE/JUDGE', 0),
  ('rnd-tax-tracker', 'Captures eligible R&D work as it happens and preps the tax-incentive claim', 'Accountancy firms', 'Claim prep', 'claim doc reads as a coherent technical narrative with activity → uncertainty → experiment mapping - not bullets of inputs', 'NAIVE/JUDGE', 1),
  ('rnd-tax-tracker', 'Captures eligible R&D work as it happens and preps the tax-incentive claim', 'Accountancy firms', 'Evidence-linked', 'click any claim line, see the source artefact (git commit, doc, transcript) - not "evidence file attached"', 'JUDGE', 2),
  ('rnd-tax-tracker', 'Captures eligible R&D work as it happens and preps the tax-incentive claim', 'Accountancy firms', 'Accountancy-fit', 'output imports directly into the accountant''s lodgement tool (or 1-step export) - not a PDF the accountant retypes', 'JUDGE', 3),
  ('cqr', 'Answers community questions in your brand voice (BYOK, free, self-host)', 'Dev shops & community operators', 'Brand voice fidelity', 'A/B blind test: ≥70% of operator''s community can''t distinguish CQR answer from operator-written - not "sounds like our brand"', 'NAIVE/JUDGE', 0),
  ('cqr', 'Answers community questions in your brand voice (BYOK, free, self-host)', 'Dev shops & community operators', 'BYOK self-host', 'clone → configure key → first answer in <10 minutes documented - not "minutes" handwave', 'AUTO/NAIVE', 1),
  ('cqr', 'Answers community questions in your brand voice (BYOK, free, self-host)', 'Dev shops & community operators', 'MIT/public', 'fork on day 1 builds and runs without contacting Dennis - not "open source with steps in the README that may work"', 'AUTO', 2),
  ('cqr', 'Answers community questions in your brand voice (BYOK, free, self-host)', 'Dev shops & community operators', 'Factory demonstration', 'CQR landing links to ≥1 paid CAIS product page with measurable referral - not standalone GitHub repo', 'JUDGE', 3),
  ('rehearsals-ai', 'AI voice coaches that play your toughest audience; practise, get scored, perfect before the moment', 'Professional associations & training orgs', 'Audience-as-AI', 'AI interrupts, asks hostile questions, expresses scepticism - not a passive listener', 'NAIVE/JUDGE', 0),
  ('rehearsals-ai', 'AI voice coaches that play your toughest audience; practise, get scored, perfect before the moment', 'Professional associations & training orgs', 'Scored practice', 'each rehearsal scored on ≥3 named axes (clarity, pace, handling pushback) with rubric visible - not a single overall score', 'NAIVE/JUDGE', 1),
  ('rehearsals-ai', 'AI voice coaches that play your toughest audience; practise, get scored, perfect before the moment', 'Professional associations & training orgs', 'Improvement over reps', 'rehearsal 5 shows measurable lift in at least one axis vs rehearsal 1 for the same user - not "you got better"', 'NAIVE/JUDGE', 2),
  ('rehearsals-ai', 'AI voice coaches that play your toughest audience; practise, get scored, perfect before the moment', 'Professional associations & training orgs', 'Member-success reflects on distributor', 'association sees member usage + outcome and can publicise wins - not a vanity dashboard', 'JUDGE', 3),
  ('launchready', 'Voice-guided IP protection for founders - automate trademark filing, capture evidence, launch with confidence', 'Accelerators & IP / legal firms', 'IP protection (not "launch prep")', 'product files the trademark application within itself (or generates the exact ready-to-lodge file) - not "here''s how to do it"', 'NAIVE/JUDGE', 0),
  ('launchready', 'Voice-guided IP protection for founders - automate trademark filing, capture evidence, launch with confidence', 'Accelerators & IP / legal firms', 'Voice-guided', 'voice agent leads the entire IP flow start-to-finish; user could be eyes-off the screen - not voice as helper button', 'NAIVE/JUDGE', 1),
  ('launchready', 'Voice-guided IP protection for founders - automate trademark filing, capture evidence, launch with confidence', 'Accelerators & IP / legal firms', 'Evidence capture', 'evidence captured includes timestamped creation artefacts (drafts, dated files) - not user-asserted dates', 'NAIVE/JUDGE', 2),
  ('launchready', 'Voice-guided IP protection for founders - automate trademark filing, capture evidence, launch with confidence', 'Accelerators & IP / legal firms', 'Confidence-to-launch', 'founder can articulate "I own X, registered on Y, in jurisdictions Z" after a session - not "I''ve started the process"', 'JUDGE', 3),
  ('launchready', 'Voice-guided IP protection for founders - automate trademark filing, capture evidence, launch with confidence', 'Accelerators & IP / legal firms', 'Distributor white-label', 'accelerator/IP firm domain, persona, branded outputs; their founders never see LaunchReady - not co-branded', 'NAIVE/JUDGE', 4),
  ('universallingo', 'Real-time translation per industry (clinics, hotels, government, education), white-label', 'Clinics, hotels, councils, schools', 'Real-time translation', 'two-way conversation flows turn-by-turn with sub-second translation per turn - not record-then-translate', 'NAIVE/JUDGE', 0),
  ('universallingo', 'Real-time translation per industry (clinics, hotels, government, education), white-label', 'Clinics, hotels, councils, schools', 'Industry-specific vocabulary', 'tested live against 20 sector-specific terms (clinical/civic/hospitality) with correct rendering - not "handles industry terms"', 'NAIVE/JUDGE', 1),
  ('universallingo', 'Real-time translation per industry (clinics, hotels, government, education), white-label', 'Clinics, hotels, councils, schools', 'Named vertical, not "every industry"', 'one landing page = one named vertical, with vertical-specific examples and case studies - not a multi-vertical homepage', 'NAIVE/JUDGE', 2),
  ('universallingo', 'Real-time translation per industry (clinics, hotels, government, education), white-label', 'Clinics, hotels, councils, schools', 'White-label', 'distributor''s domain, branding, persona, with no UL footer or attribution - not "powered by"', 'NAIVE/JUDGE', 3),
  ('tourlingo', 'Real-time, two-way translation guides use live on tour', 'Tour operators & travel companies', 'Two-way real-time translation', 'guide speaks, traveller hears native-language audio in <1.5s without unmute/replay - not transcript only', 'NAIVE/JUDGE', 0),
  ('tourlingo', 'Real-time, two-way translation guides use live on tour', 'Tour operators & travel companies', 'On-tour reliability', 'works at ≥75dB ambient + on a 3G connection without breaking - not "best in quiet room"', 'NAIVE/JUDGE', 1),
  ('tourlingo', 'Real-time, two-way translation guides use live on tour', 'Tour operators & travel companies', 'Branded for the operator', 'operator brand visible on traveller''s phone screen during use - not just on the booking page', 'NAIVE/JUDGE', 2),
  ('tourlingo', 'Real-time, two-way translation guides use live on tour', 'Tour operators & travel companies', 'Hero rewrite pending', 'hero copy names the "speak in the moment" promise above the fold + a demo button - not feature list', 'NAIVE/JUDGE', 3),
  ('outreachready', 'Researches each prospect and drafts the outreach, so every send is relevant', 'Sales agencies', 'Per-prospect research', 'dossier includes ≥5 prospect-specific signals (role, recent activity, company event, mutual ref, content trail) - not LinkedIn snippet', 'NAIVE/JUDGE', 0),
  ('outreachready', 'Researches each prospect and drafts the outreach, so every send is relevant', 'Sales agencies', 'Drafted with the research baked in', 'first sentence of every draft names a specific finding from the dossier - not generic "I saw your company"', 'NAIVE/JUDGE', 1),
  ('outreachready', 'Researches each prospect and drafts the outreach, so every send is relevant', 'Sales agencies', 'Cross-client scaling', 'agency runs ≥10 client campaigns in parallel from one console with isolated data - not one-client-at-a-time', 'JUDGE', 2),
  ('outreachready', 'Researches each prospect and drafts the outreach, so every send is relevant', 'Sales agencies', 'Hero rewrite pending', 'hero copy: "research → draft → relevant send" promise above fold with a demo - not feature paragraph', 'NAIVE/JUDGE', 3),
  ('tenderwatch', 'AI tender intelligence - matches + summarises Australian government tenders so you never miss one', 'Bid-writing & consulting firms', 'Never-miss matching', 'matches against your stated capabilities not just keywords; missed-relevance rate <5% in audit - not "matches AusTender feed"', 'AUTO/JUDGE', 0),
  ('tenderwatch', 'AI tender intelligence - matches + summarises Australian government tenders so you never miss one', 'Bid-writing & consulting firms', 'Useful summary per tender', 'summary states scope + value + deadline + go/no-go reason in ≤5 lines - not a paragraph excerpt', 'NAIVE/JUDGE', 1),
  ('tenderwatch', 'AI tender intelligence - matches + summarises Australian government tenders so you never miss one', 'Bid-writing & consulting firms', 'Retention hook for distributors', 'consulting firm runs across ≥5 client capability profiles with separated tender feeds - not single-tenant', 'JUDGE', 2),
  ('tenderwatch', 'AI tender intelligence - matches + summarises Australian government tenders so you never miss one', 'Bid-writing & consulting firms', 'ETL stable', 'ETL has run continuously for 14 days with zero gaps and is monitored - not "ETL is in progress"', 'AUTO', 3),
  ('checkpoint', 'Construction compliance + stage sign-off workflow (built by a builder, Factory2Key)', 'Modular builders & principals', 'Stage sign-off workflow', 'a stage cannot close until its required artefacts are present + signed; the system blocks - not flags', 'NAIVE/JUDGE', 0),
  ('checkpoint', 'Construction compliance + stage sign-off workflow (built by a builder, Factory2Key)', 'Modular builders & principals', 'NCC compliance baked in', 'compliance check IDs a specific NCC 2025 clause per finding - not "passes/fails compliance"', 'NAIVE/JUDGE', 1),
  ('checkpoint', 'Construction compliance + stage sign-off workflow (built by a builder, Factory2Key)', 'Modular builders & principals', 'Audit trail certifiers trust', 'certifier can read the full audit trail unaided in <5 minutes without back-and-forth - not "audit trail exists"', 'JUDGE', 2),
  ('checkpoint', 'Construction compliance + stage sign-off workflow (built by a builder, Factory2Key)', 'Modular builders & principals', 'Built-by-a-builder credibility', 'Dennis''s Factory2Key story is in the hero + a "built on our own site" proof point - not buried in About', 'JUDGE', 3),
  ('disaster-support', 'Multi-channel AI support for disaster-affected communities; agencies deploy in 24 hours', 'Disaster-recovery agencies (gov / NFP)', 'Multi-channel intake', 'same case progresses across voice, SMS, web without the person re-identifying themselves - not channel-linked accounts', 'NAIVE/JUDGE', 0),
  ('disaster-support', 'Multi-channel AI support for disaster-affected communities; agencies deploy in 24 hours', 'Disaster-recovery agencies (gov / NFP)', 'No-repeat routing', 'context carries means: zero re-asking of name, location, situation across ≥2 channels - measurable, not "less repeat"', 'NAIVE/JUDGE', 1),
  ('disaster-support', 'Multi-channel AI support for disaster-affected communities; agencies deploy in 24 hours', 'Disaster-recovery agencies (gov / NFP)', '24-hour deploy', 'agency can deploy a branded instance, configured for their event, in <24h - measurable not aspirational', 'JUDGE', 2),
  ('disaster-support', 'Multi-channel AI support for disaster-affected communities; agencies deploy in 24 hours', 'Disaster-recovery agencies (gov / NFP)', 'Coordinated triage for the agency', 'triage dashboard shows real-time prioritisation + handover state - not a contact list', 'JUDGE', 3),
  ('easy-claude-code', 'Browser dashboard to manage local Claude Code sessions - no terminals', 'Dev shops & tool vendors', 'No terminals required', 'every CC primitive (start/stop/permissions/files/diff) reachable in-browser - not "most things, fall back to terminal for the rest"', 'NAIVE/JUDGE', 0),
  ('easy-claude-code', 'Browser dashboard to manage local Claude Code sessions - no terminals', 'Dev shops & tool vendors', 'Manages LOCAL sessions', 'sessions visibly run on the developer''s machine (process list, local FS) - not ambiguous remote-vs-local', 'AUTO/JUDGE', 1),
  ('easy-claude-code', 'Browser dashboard to manage local Claude Code sessions - no terminals', 'Dev shops & tool vendors', 'Permission control', 'permission grants are per-session, scoped, auditable, and revocable mid-session - not all-or-nothing', 'NAIVE/JUDGE', 2),
  ('easy-claude-code', 'Browser dashboard to manage local Claude Code sessions - no terminals', 'Dev shops & tool vendors', 'Upload + version + push (on horizon)', 'paste-plan → versioned doc → push to a named GitHub repo in one flow - not three separate tools to glue', 'NAIVE/JUDGE', 3),
  ('easy-claude-code', 'Browser dashboard to manage local Claude Code sessions - no terminals', 'Dev shops & tool vendors', 'Team-fit for dev shops', 'dev shop admin can see + manage all their devs'' sessions from one view - not per-dev silos', 'JUDGE', 4)
ON CONFLICT (product_slug, attribute) DO UPDATE SET
  promise = EXCLUDED.promise, distributor = EXCLUDED.distributor,
  quality_bar = EXCLUDED.quality_bar, verify = EXCLUDED.verify,
  sort_order = EXCLUDED.sort_order;
